name: test-ci

on: push

jobs: 
 build:
   runs-on: ubuntu-latest
   steps:
    - name: メッセージ
      run: echo "Hello CI"
      run: echo "second run"
    - name: ファイル作成
      run: touch test.txt
      
    - name: ファイル書き込み
      run: echo "data" >test.txt
      
    - name: 内容確認
      run: cat test.txt

    - name: 一覧表示
      run: ls -l
      
 
