name: test-ci
env: 
  MY_MESSAGE: "Hello Veriable"
on: push

jobs: 
 build: 
   runs-on: ubuntu-latest
   steps:
    - name: メッセージ
      run: 
        echo $MY_MESSAGE
        echo "second run"
      
    - name: ファイル作成
      run: touch test.txt
      
    - name: ファイル書き込み
      run: echo "data" >test.txt
      
    - name: 内容確認
      run: cat test.txt

    - name: 一覧表示
      run: ls -l
      
 
