name: test-ci

env: 
  MY_MESSAGE: "Hello Veriable"
  MY_MESSAGE2: "test"

  FILENAME: "sample.txt"
  FILENAME2: "sample2.txt"

  MODE: "dev"

on: push

jobs: 
 build: 
   runs-on: ubuntu-latest
   steps:
    - run: echo"開始"
    - if: env.MODE == 'dev'
      run: "開発環境です。"
    - run: echo "テストIF終了"
    - name: メッセージ
      run: 
        echo $MY_MESSAGE
        echo "second run"
    - name: sample
      run: echo $MY_MESSAGE2 > $FILENAME
    - run: cat $FILENAME
    - run: echo  sample3 > $FILENAME2
    - run: cat $FILENAME2
    - name: ファイル作成
      run: touch test.txt
      
    - name: ファイル書き込み
      run: echo "data" >test.txt
      
    - name: 内容確認
      run: cat test.txt

    - name: 一覧表示
      run: ls -l
      
 
